# Generated by Django 4.0 on 2022-09-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crud_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=70)),
                ('sroll', models.IntegerField()),
                ('course', models.CharField(max_length=40)),
                ('doj', models.DateField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=70)),
                ('nationality', models.CharField(max_length=60)),
                ('mob', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
