# Generated by Django 4.0 on 2022-09-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud_student',
            name='mob',
            field=models.BigIntegerField(),
        ),
    ]
