# Generated by Django 4.0 on 2022-09-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0002_alter_crud_student_mob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud_student',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='crud_student',
            name='state',
            field=models.CharField(choices=[('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana')], max_length=500),
        ),
    ]
